title: IDAM.CORE
tagline: Identity & Cloud Security Practitioner
url: "https://pankajparmaar.github.io"
baseurl: "/iam-threat-model"
lang: en-US
timezone: Asia/Kolkata

# Author settings
author:
  name: Pankaj Parmar
  email: pankaj_parmar@outlook.com

# Theme layout settings
theme: jekyll-theme-chirpy

plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

# Pagination configurations
paginate: 10
paginate_path: '/page:num'

author:
  name: Pankaj Parmaar
  url: https://linkedin.com/in/pankajparmaar

avatar: /assets/img/avatar.jpg
