title: IDAM.CORE
tagline: Identity & Cloud Security Practitioner
url: https://pankajparmaar.github.io
baseurl: "/iam-threat-model"
lang: en-US
timezone: Asia/Kolkata
remote_theme: cotes2046/jekyll-theme-chirpy
theme: jekyll-theme-chirpy
